apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: gatekeeper
    meta.helm.sh/release-namespace: gatekeeper-system

  labels:
    app: gatekeeper
    app.kubernetes.io/instance: gatekeeper
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/version: 3.20.1
    chart: gatekeeper
    control-plane: audit-controller
    gatekeeper.sh/operation: audit
    gatekeeper.sh/system: "yes"
    helm.sh/chart: gatekeeper-3.20.1
    heritage: Helm
    release: gatekeeper
  name: gatekeeper-audit
  namespace: gatekeeper-system

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gatekeeper
      chart: gatekeeper
      control-plane: audit-controller
      gatekeeper.sh/operation: audit
      gatekeeper.sh/system: "yes"
      heritage: Helm
      release: gatekeeper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gatekeeper
        app.kubernetes.io/instance: gatekeeper
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: gatekeeper
        app.kubernetes.io/version: 3.20.1
        chart: gatekeeper
        control-plane: audit-controller
        gatekeeper.sh/operation: audit
        gatekeeper.sh/system: "yes"
        helm.sh/chart: gatekeeper-3.20.1
        heritage: Helm
        release: gatekeeper
    spec:
      affinity: {}
      automountServiceAccountToken: true
      containers:
      - args:
        - --audit-interval=60
        - --log-level=INFO
        - --constraint-violations-limit=20
        - --otlp-endpoint=otel-collector.default.svc.cluster.local:4318
        - --validating-webhook-configuration-name=gatekeeper-validating-webhook-configuration
        - --mutating-webhook-configuration-name=gatekeeper-mutating-webhook-configuration
        - --audit-from-cache=false
        - --audit-chunk-size=500
        - --audit-match-kind-only=false
        - --audit-events-involved-namespace=true
        - --operation=generate
        - --operation=audit
        - --operation=status
        - --operation=mutation-status
        - --logtostderr
        - --health-addr=:9090
        - --prometheus-port=8888
        - --enable-external-data=true
        - --enable-generator-resource-expansion=true
        - --metrics-backend=opentelemetry
        - --disable-cert-rotation=false
        - --external-data-provider-response-cache-ttl=3m
        - --enable-k8s-native-validation=true
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONTAINER_NAME
          value: manager
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE),k8s.container.name=$(CONTAINER_NAME)
        image: openpolicyagent/gatekeeper:v3.21.0-beta.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        ports:
        - containerPort: 8888
          name: metrics
          protocol: TCP
        - containerPort: 9090
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 999
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: cert
          readOnly: true
        - mountPath: /tmp/audit
          name: tmp-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        supplementalGroups:
        - 999
      serviceAccount: gatekeeper-admin
      serviceAccountName: gatekeeper-admin
      terminationGracePeriodSeconds: 60
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: gatekeeper-webhook-server-cert
      - emptyDir: {}
        name: tmp-volume
status:
  conditions:
  - lastTransitionTime: "2025-09-24T12:18:55Z"
    lastUpdateTime: "2025-09-24T12:19:50Z"
    message: ReplicaSet "gatekeeper-audit-5b476f6d49" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-09-24T12:35:55Z"
    lastUpdateTime: "2025-09-24T12:35:55Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
